# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Latah County
email: webmaster@latah.id.us
description: > # this means to ignore newlines until "baseurl:"
  Latah County is located in the northern Idaho panhandle; to the immediate west lies Whitman County, Washington. These counties are referred to as The Palouse, which produces a large share of the wheat, lentils, peas, oats and barley in the United States. The Palouse is home to two major universities, University of Idaho and Washington State University. Latah County incorporated cities include Bovill, Deary, Genesee, Juliaetta, Kendrick, Moscow, Onaway, Potlatch and Troy. Our unincorporated communities are Avon, Cedar Creek, Farmington, Harvard, Helmer, Howell, Joel, Princeton and Viola.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://latah.id.us" # the base hostname & protocol for your site

# Where things are.
include:
  - _pages
  - _dept
  - _admin

# Jekyll Assets settings
assets:
  prefix: "/assets"
  sources:
    -   _assets/css
    -   _assets/img
    -   _assets/js
  compress:
    css: sass
    js: uglifier
  features:
    automatic_img_alt: true
    automatic_img_size: false

# Jekyll Cloudinary settings
cloudinary:
  cloud_name: acole
  presets:
    officials:
      max_width: 500
      attributes:
        class: "img-responsive img-thumbnail"

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-assets
  - jekyll-cloudinary
